// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { createClient } from '@supabase/supabase-js';

// --- CONFIGURAÇÃO FORÇADA (PROJETO REAL: brlm...) ---
const supabaseUrl = "https://brlmkaqrmqwhapehairf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybG1rYXFybXF3aGFwZWhhaXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4NDc1NDQsImV4cCI6MjA4MTQyMzU0NH0.ndF-9aLt9CQqZQbXH4NpVD_Qzojjfe3SHIywPYrOt1k";

export const supabase = createClient(supabaseUrl, supabaseKey);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});